"""adding new model

Revision ID: 38c436456f29
Revises: 5a8ddd16171b
Create Date: 2022-11-19 14:44:40.053397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c436456f29'
down_revision = '5a8ddd16171b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'name')
    op.drop_column('authors', 'username')
    op.drop_column('authors', 'bio')
    op.add_column('profiles', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'authors', ['author_id'], ['id'])
    op.drop_column('profiles', 'password')
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'author_id')
    op.add_column('authors', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
