"""Initial migration.

Revision ID: 490aa920866a
Revises: 
Create Date: 2022-11-18 22:05:11.219483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490aa920866a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_comment', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'post_comment')
    # ### end Alembic commands ###
