"""updated profile

Revision ID: 4e9381b98bbb
Revises: 2d58391ae201
Create Date: 2022-11-19 17:23:43.909949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9381b98bbb'
down_revision = '2d58391ae201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.drop_column('profiles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'first_name')
    # ### end Alembic commands ###
