"""Updating Authors

Revision ID: 5a8ddd16171b
Revises: 82b9f7a9f931
Create Date: 2022-11-19 10:50:02.735800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8ddd16171b'
down_revision = '82b9f7a9f931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('authors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('authors', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('authors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
