"""migration.

Revision ID: 82b9f7a9f931
Revises: d41ebfea4e73
Create Date: 2022-11-19 10:38:19.685299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b9f7a9f931'
down_revision = 'd41ebfea4e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'username')
    # ### end Alembic commands ###
