"""Update

Revision ID: 8e097ae60858
Revises: e4f610e47ab2
Create Date: 2022-11-19 19:18:42.965408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e097ae60858'
down_revision = 'e4f610e47ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
