"""second migration.

Revision ID: d41ebfea4e73
Revises: 490aa920866a
Create Date: 2022-11-18 22:39:26.668432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41ebfea4e73'
down_revision = '490aa920866a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'bio')
    # ### end Alembic commands ###
