"""update

Revision ID: db693f817b3f
Revises: a3d902eeacd1
Create Date: 2022-11-19 18:47:36.205568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db693f817b3f'
down_revision = 'a3d902eeacd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
