"""updating models

Revision ID: e4f610e47ab2
Revises: db693f817b3f
Create Date: 2022-11-19 18:50:02.500251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f610e47ab2'
down_revision = 'db693f817b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.drop_constraint('posts_comment_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_comment_fkey', 'posts', 'comments', ['comment'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###
